### ISSUE TITLE
Checking In

### ISSUE THREAD

**Issue by linda-breitenstein** [linda-breitenstein/ecommerce-pattern-library#1]
@thomasjbradley
Hey Thomas!

There are a few things that  I wanted to get checked off with the eCommerce-site

1. informal accessibility testing 
2. Informal browser testing
3. Building pages with patterns
4.  The leftovers.

please let me know if out of those 4 things I am missing anything or I should go back and fix. thank you

**Comment by thomasjbradley** [comment]
Did you add any new patterns for “The Leftovers”?
