### ISSUE TITLE
Linking Images Correctly

### ISSUE THREAD

**Issue by linda-breitenstein** [linda-breitenstein/ecommerce-pattern-library#2]
Hey @mackenzierose,
I just wanted to make sure I was linking my images correctly. I'm working on Week 10 "preparing products" 

So I was hoping you could look over my _products/.md files 

Im getting an error message in terminal and i'm not able able to see any of my products when I open my local host

**Comment by linda-breitenstein** [comment]
okay, I found the images mistake. Im just having difficulty making the H1, p appearing in my products page now

**Comment by MacKenzieRose** [comment]
Given the comment on Slack, have you sorted out getting your H1 etc. to appear? (I know the colour is off, but if that's working, that's a start)

Let me know :)
MacKenzie

**Comment by MacKenzieRose** [comment]
If this issue has been addressed, please make sure to close it 😄
