### ISSUE TITLE
Preparing Product data/ Jekyll Generators

### ISSUE THREAD

**Issue by linda-breitenstein** [linda-breitenstein/ecommerce-pattern-library#3]
Hey @thomasjbradley

I just wanted to check in with you for the week 10
preparing product data 
jekyll generators

**Comment by thomasjbradley** [comment]
This code is in the wrong place, it should be inside `products.html` the page in the root folder.

https://github.com/linda-breitenstein/ecommerce-pattern-library/blob/master/_layouts/product.html#L5-L11

**Comment by linda-breitenstein** [comment]
@thomasjbradley 
whoops. okay, thank you. I switched that over.

**Comment by thomasjbradley** [comment]
👍
